### PR TITLE
Introduce custom option to disable firewall for testing purposes.

### LINKED ISSUE #4: Add disabling firewall as a custom option
We can default to "Leave firewall enabled". Some may want to disable the firewall for testing purposes, but we should leave it enabled

### PR DESCRIPTION
**Pull request by sthirugn**
Closes #4

### CODE REVIEW

**Comment by johnpmitsch** [comment]
Do we need the firewall disabled to run any of the commands in the playbook?

**Comment by sthirugn** [comment]
nope, no need to disable firewall for any task

**Comment by sthirugn** [comment]
Rebased with the recent changes

**Comment by johnpmitsch** [comment]
ACK

**Pull request merged**
