### PR TITLE
Remove jmx.conf before first installer run

### LINKED ISSUE #336: Remove jmx.conf
We need to remove `/etc/tomcat/conf.d/jmx.conf` to avoid installer issues. This was originally fixed by https://github.com/RedHatSatellite/satellite-clone/issues/290, but we should remove the file earlier, before the first installer run.

### PR DESCRIPTION
**Pull request by johnpmitsch**
Fixes #336

### CODE REVIEW

**Comment by johnpmitsch** [comment]
yee-haw

**Comment by johnpmitsch** [comment]
yee-haw

**Comment by johnpmitsch** [comment]
yee-haw

**Comment by johnpmitsch** [comment]
yee-haw

**Comment by johnpmitsch** [comment]
Merging this since it passed manually triggering dolly:
```
 192.168.121.175            : ok=21   changed=17   unreachable=0    failed=0
 192.168.121.27             : ok=21   changed=17   unreachable=0    failed=0
 192.168.121.32             : ok=21   changed=17   unreachable=0    failed=0
 192.168.121.48             : ok=21   changed=17   unreachable=0    failed=0
 192.168.121.77             : ok=21   changed=17   unreachable=0    failed=0
 192.168.121.88             : ok=22   changed=18   unreachable=0    failed=0
```

**Comment by chris1984** [comment]
yee-haw

**Pull request merged**
