### PR TITLE
Fixed hammer-setup required for foreman-maintain

### LINKED ISSUE #353: Failed to setup hammer and wont prompt user to enter credentials
If satellite backup is not having foreman-maintain hammer setup configured (/etc/foreman-maintain/foreman-maintain-hammer.yml) or wont have hammer credentials, satellite-clone will fail at

```
Upgrade Step: restart_services...
Redirecting to 'foreman-maintain service'
Running preparation steps required to run the next scenarios
================================================================================
Setup hammer: Configuring Hammer CLI...
Hammer admin password: stty: standard input: Inappropriate ioctl for device
stty: standard input: Inappropriate ioctl for device
stty: standard input: Inappropriate ioctl for device

                                                                      [FAIL]
Hammer configuration failed: Is the admin password correct? (it was stored in /etc/foreman-maintain/foreman-maintain-hammer.yml)Is the server down?
--------------------------------------------------------------------------------
Scenario [preparation steps required to run the next scenarios] failed.

The following steps ended up in failing state:

  [hammer-setup]

Resolve the failed steps and rerun
the command. In case the failures are false positives,
use --whitelist="hammer-setup"


katello-service restart failed! Check the output for error!
Upgrade step restart_services failed. Check logs for more information.
```

### PR DESCRIPTION
**Pull request by ntkathole**
Fixes #353

### CODE REVIEW

**Comment by johnpmitsch** [comment]
thanks for the PR, I'll test soon :)

**Comment by johnpmitsch** [comment]
yee-haw

**Comment by johnpmitsch** [comment]
will this just append to existing ` /etc/foreman-maintain/foreman-maintain-hammer.yml` files? For example, if I have:
```yaml
:foreman:
  :username: admin
  :password: kittens123
```
will the `lineinfile` match this? It seems like it won't and will just append new credentials to the file (this may work, but it is a bit messy if we append to the file and don't erase existing creds in it)

Since we always change the Satellite credentials to admin/changeme, I wonder if this would work better:

- move ` /etc/foreman-maintain/foreman-maintain-hammer.yml` to ` /etc/foreman-maintain/foreman-maintain-hammer.yml.satclone.backup` if it exists
- copy over a `foreman-maintain-hammer.yml` file containing `admin/changeme` config to `/etc/foreman-maintain`

**Comment by johnpmitsch** [comment]
Also, another question - Were there changes in foreman-maintain to no longer need the credentials? I remember the fact that foreman-maintain needed credentials for a service restart was a concern when we initially discussed this issue.

**Comment by johnpmitsch** [comment]
@ntkathole I didn't see you updated this! I can review soon.

Do you know an answer to this question?

> Also, another question - Were there changes in foreman-maintain to no longer need the credentials? I remember the fact that foreman-maintain needed credentials for a service restart was a concern when we initially discussed this issue.

**Comment by ntkathole** [comment]
@johnpmitsch the changes in f-m is in development. I see PR https://github.com/theforeman/foreman_maintain/pull/261 open to fix it.

**Comment by johnpmitsch** [comment]
```
PLAY RECAP *********************************************************************
192.168.121.25             : ok=21   changed=16   unreachable=0    failed=0   
192.168.121.37             : ok=21   changed=16   unreachable=0    failed=0   
192.168.121.75             : ok=21   changed=16   unreachable=0    failed=0   
192.168.121.76             : ok=21   changed=16   unreachable=0    failed=0 
```

passed automation, thanks @ntkathole!

**Pull request merged**
