### PR TITLE
shellescape all strings when disassociating capsules

### PR DESCRIPTION
**Pull request by evgeni**
Fixes: #343

### CODE REVIEW

**Comment by johnpmitsch** [comment]
Do we need anything passed into the hammer commands escaped with shell escape? i.e. a lifecycle environment name

**Comment by evgeni** [comment]
We have to escape everything that may contain chars outside of a-z0-9 (broadly speaking).

**Comment by johnpmitsch** [comment]
its also worth noting that we probably haven't ran into this for username and password because the sat-clone script resets the admin password to 'changeme' and we hardcode it in the script. I still think we should escape them like you have in case we make that step configurable.

I thought this sounded familiar, I found [this issue](https://github.com/RedHatSatellite/satellite-clone/issues/175),  in which a user has a special character in the org, breaking the script for him. We should probably address this along with the username/password

Let me know if you want to address issue #175 in this PR (escaping the organization and LEs as well), if not we can address separately.

**Comment by evgeni** [comment]
I'd argue #175 is an encoding issue, not an escaping one.

This PR does escape username, password, LE and org. I think that should be sufficient for now.

**Comment by johnpmitsch** [comment]
@evgeni thanks, I missed the shellescapes on the org and LEs, will test soon :+1:

**Comment by johnpmitsch** [comment]
yee-haw

**Comment by johnpmitsch** [comment]
yee-haw

**Comment by johnpmitsch** [comment]
changed one of the backups in dolly to be one with a capsule so the script runs :)

**Comment by johnpmitsch** [comment]
yee-haw

**Comment by johnpmitsch** [comment]
yee-haw

**Pull request merged**
