### PR TITLE
Start psql after stopping for restore

### LINKED ISSUE #146: had to start postgresql service after 6.1 RHEL7 restore
we should ensure this service is started after the installer run

### PR DESCRIPTION
**Pull request by johnpmitsch**
Fixes #146
We should ensure this service is started for sat 6.1

### CODE REVIEW

**Comment by sthirugn** [comment]
can you add a comment similar to https://github.com/johnpmitsch/satellite-clone/blob/ac8146289fc00f039b4a373941c3b8e0459bb565/roles/satellite-clone/tasks/restore.yml#L4

**Comment by johnpmitsch** [comment]
@sthirugn updated

**Comment by sthirugn** [comment]
@johnpmitsch thanks

**Comment by sthirugn** [comment]
ACK

**Pull request merged**
