### PR TITLE
Introducing helper scripts to automate the manual steps

### LINKED ISSUE #55: Create a bash script to ease setting up of Ansible control node

### PR DESCRIPTION
**Pull request by sthirugn**
Fixes #55

### CODE REVIEW

**Comment by sthirugn** [comment]
Rebased and ready for review/merge

**Comment by sthirugn** [comment]
This PR originally had the helper script + few other doc updates.  I moved the doc updates to separate new PRs - so now, this PR is really just the helper script.

**Comment by johnpmitsch** [comment]
@sthirugn not sure if this is git overriding permissions but I am getting
```
[root@rhel7 satellite-clone]# ./helpers/control_node_setup.sh
-bash: ./helpers/control_node_setup.sh: Permission denied
```
Looks like the script isn't executable
```
[root@rhel7 satellite-clone]# ls -al ./helpers/control_node_setup.sh 
-rw-r--r-- 1 root root 807 Jan 27 01:36 ./helpers/control_node_setup.sh
```
after running `chmod u+x ./helpers/control_node_setup.sh`, it ran fine and completed successfully

**Comment by sthirugn** [comment]
@johnpmitsch yes thats the intention.  You need to make it executable manually.  I am not sure if it is a right practice to have fileMode=true in git, I have always disabled that in the projects I worked on.

**Comment by sthirugn** [comment]
@johnpmitsch if it worked for you, perhaps we can merge it so it will help testers tomorrow.

**Pull request merged**
